import type { VercelRequest, VercelResponse } from '@vercel.node';

const API_KEY = process.env.API_SPORTS_KEY;

// [1. 리그 한글 매핑 리스트 - 80개 주요 대회]
const leagueNameMap: { [key: number]: string } = {
  39: "잉글랜드 프리미어리그", 40: "잉글랜드 챔피언십", 45: "잉글랜드 FA컵", 48: "EFL컵",
  140: "스페인 라리가", 141: "스페인 세군다", 143: "코파 델 레이", 147: "스페인 슈퍼컵",
  78: "독일 분데스리가", 79: "독일 2부", 81: "DFB 포칼", 529: "독일 슈퍼컵",
  135: "이탈리아 세리에 A", 136: "이탈리아 세리에 B", 137: "코파 이탈리아", 547: "이탈리아 슈퍼컵",
  61: "프랑스 리그 앙", 62: "프랑스 리그 두", 66: "쿠프 드 프랑스", 65: "프랑스 리그컵", 526: "프랑스 슈퍼컵",
  88: "네덜란드 에레디비시", 89: "네덜란드 2부", 90: "네덜란드 KNVB 베이커", 528: "네덜란드 슈퍼컵",
  179: "스코틀랜드 프리미어십", 180: "스코틀랜드 2부", 94: "포르투갈 프리메이라리가", 95: "포르투갈 2부", 96: "타사 드 포르투갈", 210: "포르투갈 리그컵", 550: "포르투갈 슈퍼컵",
  203: "튀르키예 수페르리그", 204: "튀르키예 1.리그", 205: "튀르키예 컵", 551: "튀르키예 슈퍼컵", 197: "그리스 슈퍼리그 1", 106: "폴란드 엑스트라클라사", 103: "노르웨이 엘리테세리엔", 119: "덴마크 수페르리가", 172: "불가리아 1부", 271: "헝가리 1부", 218: "크로아티아 1부", 144: "벨기에 프로리그", 207: "스위스 슈퍼리그", 357: "아일랜드 프리미어",
  292: "K리그 1", 293: "K리그 2", 295: "KFA 코리아컵", 98: "J1 리그", 99: "J2 리그", 102: "일본 천황배", 101: "J리그컵", 530: "일본 슈퍼컵", 169: "중국 슈퍼리그", 170: "중국 2부", 171: "중국 FA컵", 188: "호주 A리그", 189: "호주 FFA컵", 323: "베트남 V리그 1", 296: "태국 1부", 307: "사우디 프로리그", 323: "인도 슈퍼리그", 274: "인도네시아 1부", 305: "카타르 스타스 리그", 301: "UAE 프로리그", 280: "말레이시아 슈퍼리그", 310: "요르단 1부",
  253: "미국 MLS", 255: "미국 USL 챔피언십", 262: "멕시코 리가 MX", 71: "브라질 세리에 A", 1579: "캐나다 프리미어", 128: "아르헨티나 리가 프로페셔널", 268: "우루과이 1부", 281: "페루 1부", 239: "콜롬비아 1부", 265: "칠레 1부", 242: "에콰도르 1부", 252: "파라과이 1부",
  2: "UEFA 챔피언스리그", 3: "UEFA 유로파리그", 848: "UEFA 컨퍼런스리그", 17: "AFC 챔피언스리그", 1: "월드컵", 5: "UEFA 네이션스리그", 9: "아시안컵", 134: "동아시안컵"
};

// [2. 주요 150개 팀 한글 매핑 리스트]
// 사장님, 아래 리스트에 없는 팀은 자동으로 영문명이 노출됩니다. 
// 나중에 영문명을 보고 여기에 한 줄씩 추가만 하시면 바로 한글로 바뀝니다.
const teamNameMap: { [key: string]: string } = {
  // 프리미어리그
  "Arsenal": "아스널", "Aston Villa": "아스톤 빌라", "Bournemouth": "본머스", "Brentford": "브렌트포드", "Brighton": "브라이튼", "Chelsea": "첼시", "Crystal Palace": "크리스탈 팰리스", "Everton": "에버턴", "Fulham": "풀럼", "Ipswich": "입스위치", "Leicester": "레스터", "Liverpool": "리버풀", "Manchester City": "맨시티", "Manchester United": "맨유", "Newcastle": "뉴캐슬", "Nottingham Forest": "노팅엄", "Southampton": "사우샘프턴", "Tottenham": "토트넘", "West Ham": "웨스트햄", "Wolves": "울버햄튼",
  // 라리가
  "Alaves": "알라베스", "Athletic Club": "빌바오", "Atletico Madrid": "AT 마드리드", "Barcelona": "바르셀로나", "Celta Vigo": "셀타 비고", "Espanyol": "에스파뇰", "Getafe": "헤타페", "Girona": "지로나", "Las Palmas": "라스팔마스", "Leganes": "레가네스", "Mallorca": "마요르카", "Osasuna": "오사수나", "Ray오 Vallecano": "라요", "Real Betis": "베티스", "Real Madrid": "레알 마드리드", "Real Sociedad": "소시에다드", "Sevilla": "세비야", "Valencia": "발렌시아", "Valladolid": "바야돌리드", "Villarreal": "비야레알",
  // 분데스리가
  "Augsburg": "아우크스부르크", "Bayer Leverkusen": "레버쿠젠", "Bayern Munich": "바이에른 뮌헨", "Borussia Dortmund": "도르트문트", "Borussia Monchengladbach": "글라트바흐", "Eintracht Frankfurt": "프랑크푸르트", "SC Freiburg": "프라이부르크", "Heidenheim": "하이덴하임", "Hoffenheim": "호펜하임", "Holstein Kiel": "홀슈타인 킬", "RB Leipzig": "라이프치히", "FSV Mainz 05": "마인츠", "St. Pauli": "상파울루", "Stuttgart": "슈투트가르트", "Union Berlin": "우니온 베를린", "Werder Bremen": "브레멘", "Wolfsburg": "볼프스부르크",
  // 세리에 A
  "AC Milan": "AC 밀란", "Atalanta": "아탈란타", "Bologna": "볼로냐", "Cagliari": "칼리아리", "Como": "코모", "Empoli": "엠폴리", "Fiorentina": "피오렌티나", "Genoa": "제노아", "Inter": "인테르", "Juventus": "유벤투스", "Lazio": "라치오", "Lecce": "레체", "Monza": "몬차", "Napoli": "나폴리", "Parma": "파르마", "Roma": "AS 로마", "Torino": "토리노", "Udinese": "우디네세", "Venezia": "베네치아", "Verona": "베로나",
  // 리그 앙
  "Auxerre": "오세르", "Angers": "앙제", "Brest": "브레스투아", "Le Havre": "르아브르", "Lens": "랑스", "Lille": "릴", "Lyon": "리옹", "Marseille": "마르세유", "Monaco": "모나코", "Montpellier": "몽펠리에", "Nantes": "낭트", "Nice": "니스", "Paris Saint Germain": "PSG", "Reims": "랭스", "Rennes": "렌", "Saint Etienne": "생테티엔", "Strasbourg": "스트라스부르", "Toulouse": "툴루즈",
  // K리그 1
  "Ulsan HD": "울산 HD", "Pohang Steelers": "포항", "Gwangju FC": "광주", "Jeonbuk Motors": "전북", "Daegu FC": "대구", "Incheon United": "인천", "FC Seoul": "FC 서울", "Daejeon Citizen": "대전", "Jeju United": "제주", "Gangwon FC": "강원", "Suwon FC": "수원 FC", "Gimcheon Sangmu": "김천 상무"
  // 일괄
  "Manchester United": "맨체스터 유나이티드",
"Bayern Munich": "바이에른 뮌헨",
"Juventus": "유벤투스",
"Benfica": "벤피카",
"FC Porto": "FC 포르투",
"Sporting CP": "스포르팅 CP",
"SC Braga": "브라가",
"Guimaraes": "비토리아 기마랑이스",
"Moreirense": "모레이렌세",
"Arouca": "아로카",
"Famalicao": "파말리캉",
"Casa Pia": "카사 피아",
"Farense": "파렌세",
"Rio Ave": "히우 아브",
"Gil Vicente": "질 비센트",
"Estoril": "에스토릴",
"Boavista": "보아비스타",
"Estrela": "이스트렐라",
"AVS": "AVS",
"Santa Clara": "산타 클라라",
"Nacional": "나시오날",
"Portimonense": "포르티모넨세",
"Vizela": "비젤라",
"Chaves": "샤베스",
"Maritimo": "마리티무",
"Pacos de Ferreira": "파수스 드 페헤이라",
"Tondela": "톤델라",
"Torreense": "토렌세",
"Benfica B": "벤피카 B",
"Mafra": "마프라",
"Porto B": "포르투 B",
"Leixoes": "레이숑이스 (레이소에스)",
"Alverca": "알베르카",
"Feirense": "페이렌세",
"Academico Viseu": "아카데미코 비제우",
"Penafiel": "페나피엘",
"Felgueiras": "펠게이라스",
"Oliveirense": "올리베이렌세",
"Leiria": "레이리아",
"Galatasaray": "갈라타사라이",
"Fenerbahce": "페네르바흐체",
"Besiktas": "베식타시",
"Trabzonspor": "트라브존스포르",
"Basaksehir": "바샥셰히르",
"Kasimpasa": "카슴파샤",
"Alanyaspor": "알라니아스포르",
"Antalyaspor": "안탈리아스포르",
"Sivasspor": "시바스스포르",
"Rizespor": "리제스포르",
"Konyaspor": "코냐스포르",
"Gaziantep FK": "가지안테프 FK",
"Göztepe": "괴즈테페",
"Eyupspor": "에위프스포르",
"Samsunspor": "삼순스포르",
"Bodrumspor": "보드룸스포르",
"Hatayspor": "하타이스포르",
"Kayserispor": "카이세리스포르",
"Ankaragucu": "앙카라귀쥐",
"Pendikspor": "펜디크스포르",
"Karagumruk": "카라귐뤼크",
"Istanbulspor": "이스탄불스포르",
"Corum FK": "초룸 FK",
"Kocaelispor": "코자엘리스포르",
"Sakaryaspor": "사카리아스포르",
"Genclerbirligi": "겐츨레르비를리이",
"Boluspor": "볼루스포르",
"Bandirmaspor": "반드르마스포르",
"Erzurumspor": "에르주룸스포르",
"Manisa FK": "마니사 FK",
"Ümraniyespor": "움라니예스포르",
"Keçiörengücü": "케치외렌귀쥐",
"Igdir FK": "이그디르 FK",
"Esenler Erokspor": "에센레르 에록스포르",
"Amed SK": "아메드 SK",
"Sanliurfaspor": "샨리우르파스포르",
"PAOK": "PAOK (파오크)",
"AEK Athens": "AEK 아테네",
"Olympiacos": "올림피아코스",
"Panathinaikos": "파나티나이코스",
"Aris": "아리스",
"Lamia": "라미아",
"Asteras Tripolis": "아스테라스 트리폴리스",
"Panserraikos": "판세라이코스",
"OFI Crete": "OFI 크레타",
"Atromitos": "아트로미토스",
"Panetolikos": "파네톨리코스",
"Volos": "볼로스",
"Levadiakos": "레바디아코스",
"Athens Kallithea": "아테네 칼리테아",
"Jagiellonia Bialystok": "야기엘로니아 비아위스토크",
"Slask Wroclaw": "슬롱스크 브로츠와프",
"Legia Warszawa": "레기아 바르샤바",
"Lech Poznan": "레흐 포즈난",
"Pogon Szczecin": "포곤 슈체친",
"Rakow Czestochowa": "라쿠프 쳉스토호바",
"Gornik Zabrze": "구르니크 자브제",
"Stal Mielec": "스탈 미엘레츠",
"Widzew Lodz": "비제프 우치",
"Piast Gliwice": "피아스트 글리비체",
"Zaglebie Lubin": "자글렝비에 루빈",
"Cracovia": "크라코비아",
"Radomiak Radom": "라도미아크 라돔",
"Puszcza Niepolomice": "푸슈차 니에폴로미체",
"Lechia Gdansk": "레히아 그단스크",
"GKS Katowice": "GKS 카토비체",
"Motor Lublin": "모토르 루블린",
"Bodo/Glimt": "보되/글림트",
"Molde": "몰데",
"Viking": "비킹",
"Brann": "브란",
"Rosenborg": "로젠보리",
"Tromso": "트롬쇠",
"Lillestrom": "릴레스트롬",
"Sarpsborg 08": "사릅스보르그 08",
"Stromsgodset": "스트룀스고드셋",
"Odd": "오드",
"Ham-Kam": "함캄",
"FK Haugesund": "하우게순",
"Fredrikstad": "프레드릭스타드",
"KFUM Oslo": "KFUM 오슬로",
"Sandefjord": "산데피오르",
"Kristiansund": "크리스티안순",
"FC Copenhagen": "FC 코펜하겐",
"FC Midtjylland": "FC 미트윌란",
"Brondby": "브뢴뷔",
"FC Nordsjaelland": "FC 노르셸란",
"AGF Aarhus": "AGF 오르후스",
"Silkeborg": "실케보르",
"Viborg": "비보르",
"Odense": "오덴세",
"Randers FC": "란데르스 FC",
"Vejle": "바일레",
"Sonderjyske": "쇤데르위스케",
"Aalborg": "올보르",
"Ludogorets": "루도고레츠",
"CSKA Sofia": "CSKA 소피아",
"Cherno More": "체르노 모레",
"Levski Sofia": "레프스키 소피아",
"Lokomotiv Plovdiv": "로코모티브 플로브디프",
"CSKA 1948": "CSKA 1948",
"Arda Kardzhali": "아르다 카르잘리",
"Botev Plovdiv": "보테프 플로브디프",
"Slavia Sofia": "슬라비아 소피아",
"Beroe": "베로에",
"Hebar 1918": "헤바르 1918",
"Krumovgrad": "크루모브그라드",
"Spartak Varna": "스파르타크 바르나",
"Septemvri Sofia": "세프템브리 소피아",
"Ferencvaros": "페렌츠바로시",
"Paksi SE": "팍시 SE",
"Fehervar FC": "페헤르바르 FC",
"Puskas Academia": "푸스카스 아카데미아",
"Debrecen": "데브레첸",
"MTK Budapest": "MTK 부다페스트",
"Diosgyor": "디오시죄르",
"Zalaegerszeg": "잘러에게르세그",
"Kecskemeti TE": "케치케메트 TE",
"Ujpest": "우이페슈트",
"Nyiregyhaza": "니레지하저",
"Gyor": "죄르",
"Dinamo Zagreb": "디나모 자그레브",
"Rijeka": "리예카",
"Hajduk Split": "하이두크 스플리트",
"Osijek": "오시예크",
"Lokomotiva Zagreb": "로코모티바 자그레브",
"Varazdin": "바라즈딘",
"Gorica": "고리차",
"Istra 1961": "이스트라 1961",
"Slaven Belupo": "슬라벤 벨루포",
"Sibenik": "시베니크",
"Club Brugge KV": "클뤼프 브뤼허",
"Union St. Gilloise": "위니옹 생질루아즈",
"Anderlecht": "안데를레흐트",
"Antwerp": "앤트워프",
"Genk": "헹크",
"Gent": "헨트",
"Cercle Brugge KSV": "세르클 브뤼허",
"Mechelen": "메헬렌",
"Sint-Truiden": "신트트라위던",
"Standard Liege": "스탕다르 리에주",
"Westerlo": "베스테를로",
"Sporting Charleroi": "스포르팅 샤를루아",
"Kortrijk": "코르트레이크",
"RWDM": "RWDM",
"Beerschot VA": "비어스호트 VA",
"Dender": "덴데르",
"Young Boys": "영 보이스",
"Servette": "세르베트",
"Lugano": "루가노",
"FC Zurich": "FC 취리히",
"St. Gallen": "장크트갈렌",
"Winterthur": "빈터투어",
"FC Luzern": "FC 루체른",
"Basel": "바젤",
"Grasshopper": "그라스호퍼",
"Yverdon": "이베르동",
"Lausanne Sport": "로잔 스포르",
"Sion": "시옹",
"Shamrock Rovers": "샴록 로버스",
"Derry City": "데리 시티",
"St. Patricks": "세인트 패트릭스",
"Shelbourne": "셸본",
"Dundalk": "던독",
"Bohemians": "보헤미안스",
"Sligo Rovers": "슬라이고 로버스",
"Galway United": "골웨이 유나이티드",
"Waterford": "워터퍼드",
"Drogheda United": "드로헤다 유나이티드",
"PSV Eindhoven": "PSV 에인트호번",
"Feyenoord": "페예노르트",
"Twente": "트벤테",
"AZ Alkmaar": "AZ 알크마르",
"Ajax": "아약스",
"NEC Nijmegen": "NEC 네이메헌",
"Utrecht": "위트레흐트",
"Sparta Rotterdam": "스파르타 로테르담",
"Go Ahead Eagles": "고 어헤드 이글스",
"Fortuna Sittard": "포르투나 시타르트",
"Heerenveen": "헤이렌베인",
"PEC Zwolle": "PEC 즈볼러",
"Almere City": "알메러 시티",
"Heracles": "헤라클레스",
"Waalwijk": "발베이크",
"Willem II": "빌럼 II",
"Groningen": "흐로닝언",
"NAC Breda": "NAC 브레다",
"Vitesse": "비테세",
"Volendam": "볼렌담",
"Excelsior": "엑셀시오르",
"Roda": "로다",
"Dordrecht": "도르드레흐트",
"ADO Den Haag": "ADO 덴하흐",
"De Graafschap": "더 흐라프스합",
"Emmen": "에먼",
"Maastricht": "마스트리흐트",
"Cambuur": "캄뷔르",
"VVV Venlo": "VVV 펜로",
"Helmond Sport": "헬몬트 스포르트",
"Telstar": "텔스타",
"TOP Oss": "TOP 오스",
"FC Eindhoven": "FC 에인트호번",
"Den Bosch": "덴보스",
"Jong PSV": "용 PSV",
"Jong Ajax": "용 아약스",
"Jong AZ": "용 AZ",
"Jong Utrecht": "용 위트레흐트",
"Celtic": "셀틱",
"Rangers": "레인저스",
"Hearts": "하츠",
"Kilmarnock": "킬마녹",
"St. Mirren": "세인트 미렌",
"Dundee FC": "던디 FC",
"Aberdeen": "애버딘",
"Motherwell": "마더웰",
"Hibernian": "히버니언",
"Ross County": "로스 카운티",
"St. Johnstone": "세인트 존스톤",
"Dundee Utd": "던디 유나이티드",
"Livingston": "리빙스턴",
"Raith Rovers": "레이스 로버스",
"Partick Thistle": "파틱 시슬",
"Airdrieonians": "에어드리오니언스",
"Falkirk": "폴커크",
"Hamilton Academical": "해밀턴 아카데미컬",
"Greenock Morton": "그리녹 모턴",
"Dunfermline": "던펌린",
"Queen's Park": "퀸스 파크",
"Ayr United": "에어 유나이티드",
"Central Coast Mariners": "센트럴 코스트 매리너스",
"Melbourne Victory": "멜버른 빅토리",
"Sydney FC": "시드니 FC",
"Macarthur FC": "맥아더 FC",
"Wellington Phoenix": "웰링턴 피닉스",
"Melbourne City": "멜버른 시티",
"Western Sydney Wanderers": "웨스턴 시드니 원더러스",
"Adelaide United": "애들레이드 유나이티드",
"Brisbane Roar": "브리즈번 로어",
"Perth Glory": "퍼스 글로리",
"Newcastle Jets": "뉴캐슬 제츠",
"Western United": "웨스턴 유나이티드",
"Auckland FC": "오클랜드 FC",
"Nam Dinh": "남딘",
"Binh Dinh": "빈딘",
"Ha Noi FC": "하노이 FC",
"The Cong-Viettel": "더콩-비엣텔",
"Cong An Ha Noi": "공안 하노이",
"Hai Phong": "하이퐁",
"Binh Duong": "빈즈엉",
"Hong Linh Ha Tinh": "홍린 하띤",
"Dong A Thanh Hoa": "동아 타인호아",
"TP Ho Chi Minh": "호치민 시티",
"Hoang Anh Gia Lai": "호앙아인 잘라이",
"Song Lam Nghe An": "송람 응에안",
"Quang Nam": "꽝남",
"SHB Da Nang": "SHB 다낭",
"Buriram United": "부리람 유나이티드",
"Bangkok United": "방콕 유나이티드",
"Port FC": "포트 FC",
"BG Pathum United": "BG 빠툼 유나이티드",
"Muang Thong United": "무앙통 유나이티드",
"Ratchaburi": "랏차부리",
"Chiangrai United": "치앙라이 유나이티드",
"Khon Kaen United": "콘깬 유나이티드",
"Lamphun Warriors": "람푼 워리어스",
"Uthai Thani": "우타이타니",
"Sukhothai": "수코타이",
"Nakhon Pathom": "나콘파톰",
"Prachuap": "쁘라추압",
"Nakhon Ratchasima": "나콘랏차시마",
"Nong Bua Pitchaya": "농부아 피차야",
"Rayong": "라용",
"Al-Hilal Saudi FC": "알 힐랄",
"Al-Nassr": "알 나스르",
"Al Ahli": "알 아흘리",
"Al Taawon": "알 타아운",
"Al-Ittihad FC": "알 이티하드",
"Al Ettifaq": "알 이티파크",
"Al Fateh": "알 파테흐",
"Al Shabab": "알 샤바브",
"Al-Fayha": "알 파이하",
"Damac": "다막",
"Al Khaleej": "알 칼리지",
"Al Wehda": "알 웨흐다",
"Al Riyadh": "알 리야드",
"Al Akhdoud": "알 아크두드",
"Al Raed": "알 라에드",
"Al Qadisiyah": "알 카디시야",
"Al Kholood": "알 콜루드",
"Al Orubah": "알 오루바",
"Mohun Bagan": "모훈 바간",
"Mumbai City": "뭄바이 시티",
"FC Goa": "FC 고아",
"Odisha FC": "오디샤 FC",
"Kerala Blasters": "케랄라 블래스터스",
"Chennaiyin": "첸나이인",
"NorthEast United": "노스이스트 유나이티드",
"East Bengal": "이스트 벵골",
"Punjab": "펀자브",
"Bengaluru": "벵갈루루",
"Jamshedpur": "잠셰드푸르",
"Hyderabad": "하이데라바드",
"Mohammedan": "모하메단",
"Borneo": "보르네오",
"Persib Bandung": "페르십 반둥",
"Bali United": "발리 유나이티드",
"Madura United": "마두라 유나이티드",
"Dewa United": "데와 유나이티드",
"PSIS Semarang": "PSIS 스마랑",
"Persis Solo": "페르시스 솔로",
"Persija Jakarta": "페르시자 자카르타",
"Persik Kediri": "페르식 케디리",
"Barito Putera": "바리토 푸테라",
"Persebaya": "페르세바야",
"PSM Makassar": "PSM 마카사르",
"PSS Sleman": "PSS 슬레만",
"Arema": "아레마",
"Semen Padang": "세멘 파당",
"PSBS Biak": "PSBS 비악",
"Malut United": "말루트 유나이티드",
"Al Sadd": "알 사드",
"Al-Duhail SC": "알 두하일",
"Al-Gharafa": "알 가라파",
"Al Wakrah": "알 와크라",
"Al-Arabi SC": "알 아라비",
"Al-Rayyan SC": "알 라이얀",
"UMM Salal": "움 살랄",
"Al Ahli Doha": "알 아흘리 도하",
"Qatar SC": "카타르 SC",
"Al Shamal": "알 샤말",
"Al-Khor": "알 코르",
"Al Shahaniya": "알 샤하니야",
"Al-Wasl": "알 와슬",
"Shabab Al Ahli": "샤밥 알 아흘리",
"Al-Ain": "알 아인",
"Al-Sharjah": "알 샤르자",
"Al Wahda": "알 와흐다",
"Al-Nasr": "알 나스르",
"Al-Bataeh": "알 바타에흐",
"Al-Ittihad Kalba": "칼바",
"Bani Yas": "바니야스",
"Ajman": "아지만",
"Khorfakkan": "코르파칸",
"Al-Jazira": "알 자지라",
"Al-Uruba": "알 우루바",
"Dibba Al Hisn": "딥바 알 히슨",
"Johor Darul Ta'zim": "조호르 다룰 타짐",
"Selangor": "슬랑오르",
"Terengganu": "트렝가누",
"Sabah": "사바",
"Kedah": "케다",
"Kuala Lumpur City": "쿠알라룸푸르 시티",
"PDRM": "PDRM",
"Sri Pahang": "스리 파항",
"Perak": "페락",
"Penang": "페낭",
"Kuching City": "쿠칭 시티",
"Negeri Sembilan": "느그리 셈빌란",
"Kelantan Darul Naim": "클란탄 다룰 나임",
"Al-Faisaly Amman": "알 파이살리 암만",
"Al-Wehdat": "알 웨흐다트",
"Al-Hussein": "알 후세인",
"Ramtha": "람타",
"Shabab Al-Ordon": "샤밥 알 오르돈",
"Al-Jazeera Amman": "알 자지라 암만",
"Al-Salt": "알 살트",
"Ma'an": "마안",
"Moghayer Al-Sarhan": "모가예르 알 사르한",
"Al-Ahli Amman": "알 아흘리 암만",
"Al-Sareeh": "알 사리흐",
"Al-Baqa'a": "알 바카아",
"Inter Miami": "인터 마이애미",
"Columbus Crew": "콜럼버스 크루",
"Los Angeles FC": "LA FC",
"LA Galaxy": "LA 갤럭시",
"FC Cincinnati": "FC 신시내티",
"Real Salt Lake": "레알 솔트레이크",
"New York City FC": "뉴욕 시티 FC",
"New York Red Bulls": "뉴욕 레드불스",
"Orlando City SC": "올랜도 시티",
"Houston Dynamo": "휴스턴 다이너모",
"Seattle Sounders": "시애틀 사운더스",
"Colorado Rapids": "콜로라도 래피즈",
"Vancouver Whitecaps": "밴쿠버 화이트캡스",
"Portland Timbers": "포틀랜드 팀버스",
"Charlotte FC": "샬럿 FC",
"Minnesota United": "미네소타 유나이티드",
"St. Louis City SC": "세인트루이스 시티",
"Atlanta United": "애틀랜타 유나이티드",
"FC Dallas": "FC 댈러스",
"Philadelphia Union": "필라델피아 유니언",
"Nashville SC": "내슈빌 SC",
"Austin FC": "오스틴 FC",
"D.C. United": "DC 유나이티드",
"New England Revolution": "뉴잉글랜드 레볼루션",
"Toronto FC": "토론토 FC",
"Sporting Kansas City": "스포르팅 캔자스시티",
"Chicago Fire": "시카고 파이어",
"San Jose Earthquakes": "산호세 어스퀘이크스",
"Club America": "클루브 아메리카",
"Cruz Azul": "크루스 아술",
"Tigres UANL": "티그레스 UANL",
"Monterrey": "몬테레이",
"Guadalajara (Chivas)": "과달라하라 (치바스)",
"Pumas UNAM": "푸마스 UNAM",
"Toluca": "톨루카",
"Pachuca": "파추카",
"Leon": "레온",
"Santos Laguna": "산토스 라구나",
"Tijuana": "티후아나",
"Atlas": "아틀라스",
"Queretaro": "케레타로",
"Necaxa": "네카사",
"Mazatlan FC": "마사틀란 FC",
"FC Juarez": "FC 후아레스",
"Puebla": "푸에블라",
"Atletico San Luis": "아틀레티코 산루이스",
"Forge FC": "포지 FC",
"Cavalry FC": "캐벌리 FC",
"Pacific FC": "퍼시픽 FC",
"York United": "요크 유나이티드",
"Atletico Ottawa": "아틀레티코 오타와",
"Valour FC": "발루어 FC",
"Vancouver FC": "밴쿠버 FC",
"Halifax Wanderers": "핼리팩스 원더러스",
"Palmeiras": "파우메이라스",
"Flamengo": "플라멩구",
"Botafogo": "보타포구",
"Fortaleza": "포르탈레자",
"Sao Paulo": "상파울루",
"Internacional": "인테르나시오나우",
"Cruzeiro": "크루제이루",
"Bahia": "바이아",
"Vasco da Gama": "바스쿠 다 가마",
"Atletico Mineiro": "아틀레치쿠 미네이루",
"Gremio": "그레미우",
"Corinthians": "코린치앙스",
"Athletico Paranaense": "아틀레치쿠 파라나엔시",
"Fluminense": "플루미넨시",
"Cuiaba": "쿠이아바",
"Vitoria": "비토리아",
"Juventude": "주벤투지",
"Bragantino": "브라간치누",
"Criciuma": "크리시우마",
"Atletico Goianiense": "아틀레치쿠 고이아니엔시",
"River Plate": "리버 플레이트",
"Boca Juniors": "보카 주니어스",
"Racing Club": "라싱 클루브",
"Talleres Cordoba": "탈레레스 코르도바",
"Huracan": "우라칸",
"Union": "우니온",
"Atletico Tucuman": "아틀레티코 투쿠만",
"Velez Sarsfield": "벨레스 사르스필드",
"Estudiantes": "에스투디안테스",
"Independiente": "인디펜디엔테",
"Lanus": "라누스",
"Belgrano": "벨그라노",
"Godoy Cruz": "고도이 크루스",
"San Lorenzo": "산로렌소",
"Newell's Old Boys": "뉴웰스 올드 보이스",
"Rosario Central": "로사리오 센트랄",
"Aguilas Doradas": "아길라스 도라다스",
"Alianza": "알리안사",
"America de Cali": "아메리카 데 칼리",
"Atlético Bucaramanga": "아틀레티코 부카라망가",
"Atlético Nacional": "아틀레티코 나시오날",
"Boyacá Chicó": "보야카 치코",
"Deportes Tolima": "데포르테스 톨리마",
"Deportivo Cali": "데포르티보 칼리",
"Deportivo Pasto": "데포르티보 파스토",
"Deportivo Pereira": "데포르티보 페레이라",
"Envigado": "엔비가도",
"Fortaleza CEIF": "포르탈레사 CEIF",
"Independiente Medellín": "인디펜디엔테 메데인",
"Jaguares de Córdoba": "하과레스 데 코르도바",
"Junior": "주니오르",
"La Equidad": "라 에키다드",
"Millonarios": "미요나리오스",
"Once Caldas": "온세 칼다스",
"Patriotas Boyacá": "파트리오타스 보야카",
"Santa Fe": "산타페",
"Audax Italiano": "아우닥스 이탈리아노",
"Cobreloa": "코브렐로아",
"Cobresal": "코브레살",
"Colo Colo": "콜로콜로",
"Coquimbo Unido": "코킴보 우니도",
"Deportes Copiapó": "데포르테스 코피아포",
"Deportes Iquique": "데포르테스 이키케",
"Everton de Viña del Mar": "에버턴 데 비냐 델 마르",
"Huachipato": "우아치파토",
"Ñublense": "뉴블렌세",
"O'Higgins": "오이긴스",
"Palestino": "팔레스티노",
"Unión Española": "우니온 에스파뇰라",
"Unión La Calera": "우니온 라 칼레라",
"Universidad Catolica": "우니베르시다드 카톨리카",
"Universidad de Chile": "우니베르시다드 데 칠레",
"Aucas": "아우카스",
"Barcelona SC": "바르셀로나 SC",
"Cumbayá": "쿰바야",
"Deportivo Cuenca": "데포르티보 쿠엥카",
"Delfin": "델핀",
"El Nacional": "엘 나시오날",
"Imbabura": "임바부라",
"Independiente del Valle": "인디펜디엔테 델 바예",
"LDU Quito": "LDU 키토",
"Libertad": "리베르타드",
"Macará": "마카라",
"Mushuc Runa": "무슈크 루나",
"Orense": "오렌세",
"Técnico Universitario": "테크니코 우니베르시타리오",
"Universidad Católica": "우니베르시다드 카톨리카",
"Vía del Mar": "비아 델 마르",
"2 de Mayo": "2 데 마요",
"Cerro Porteño": "세로 포르테뇨",
"General Caballero JLM": "헤네랄 카바예로 JLM",
"Guaraní": "과라니",
"Libertad": "리베르타드",
"Nacional Asunción": "나시오날 아순시온",
"Olimpia": "올림피아",
"Sol de América": "솔 데 아메리카",
"Sportivo Ameliano": "스포르티보 아멜리아노",
"Sportivo Luqueño": "스포르티보 루케뇨",
"Sportivo Trinidense": "스포르티보 트리니덴세",
"Tacuary": "타쿠아리",
"Boston River": "보스턴 리버",
"Cerro": "세로",
"Cerro Largo": "세로 라르고",
"Danubio": "다누비오",
"Defensor Sporting": "데펜소르 스포르팅",
"Deportivo Maldonado": "데포르티보 말도나도",
"Fénix": "페닉스",
"Liverpool M.": "리버풀 몬테비데오",
"Miramar Misiones": "미라마르 미시오네스",
"Montevideo Wanderers": "몬테비데오 원더러스",
"Nacional": "나시오날",
"Peñarol": "페냐롤",
"Progreso": "프로그레소",
"Racing": "라싱",
"Rampla Juniors": "람플라 주니어스",
"River Plate": "리버 플레이트",
"ADT": "ADT",
"Alianza Atlético": "알리안사 아틀레티코",
"Alianza Lima": "알리안사 리마",
"Atlético Grau": "아틀레티코 그라우",
"Carlos Mannucci": "카를로스 만누치",
"Cienciano": "시엔시아노",
"Comerciantes Unidos": "코메르시안테스 우니도스",
"Cusco": "쿠스코",
"Deportivo Garcilaso": "데포르티보 가르실라소",
"Los Chankas": "로스 찬카스",
"Melgar": "멜가르",
"Sport Boys": "스포르트 보이스",
"Sport Huancayo": "스포르트 우앙카요",
"Sporting Cristal": "스포르팅 크리스탈",
"Tarma": "타르마",
"Unión Comercio": "우니온 코메르시오",
"UTC": "UTC",
"Universitario": "우니베르시타리오",
"Always Ready": "올웨이즈 레디",
"Aurora": "아우로라",
"Blooming": "블루밍",
"Bolívar": "볼리바르",
"Guabirá": "과비라",
"Gualberto Villarroel": "과알베르토 비야로엘",
"Independiente Petrolero": "인디펜디엔테 페트롤레로",
"Nacional Potosí": "나시오날 포토시",
"Oriente Petrolero": "오리엔테 페트롤레로",
"Real Santa Cruz": "레알 산타크루스",
"Real Tomayapo": "레알 토마야포",
"Royal Pari": "로열 파리",
"San Antonio": "산 안토니오",
"The Strongest": "더 스트롱기스트",
"Universitario de Vinto": "우니베르시타리오 데 빈토",
"Wilstermann": "윌스테르만",
"Blackburn": "블랙번",
"Bristol City": "브리스톨 시티",
"Burnley": "번리",
"Cardiff": "카디프",
"Coventry": "코번트리",
"Derby": "더비 카운티",
"Hull City": "헐 시티",
"Luton": "루턴",
"Middlesbrough": "미들즈브러",
"Millwall": "밀월",
"Norwich": "노리치",
"Oxford United": "옥스퍼드 유나이티드",
"Plymouth": "플리머스",
"Portsmouth": "포츠머스",
"Preston": "프레스턴",
"QPR": "QPR",
"Sheffield Utd": "셰필드 유나이티드",
"Sheffield Wednesday": "셰필드 웬즈데이",
"Stoke City": "스토크 시티",
"Sunderland": "선덜랜드",
"Swansea": "스완지",
"Watford": "왓포드",
"West Brom": "웨스트 브롬",
"Leeds": "리즈",
"Albacete": "알바세테",
"Almeria": "알메리아",
"Burgos": "부르고스",
"Cadiz": "카디스",
"Cartagena": "카르타헤나",
"Castellon": "카스테욘",
"Cordoba": "코르도바",
"Deportivo La Coruna": "데포르티보 라코루냐",
"Eibar": "에이바르",
"Eldense": "엘덴세",
"Elche": "엘체",
"Ferrol": "페롤",
"Gijon": "히혼",
"Granada": "그라나다",
"Huesca": "우에스카",
"Levante": "레반테",
"Malaga": "말라가",
"Mirandes": "미란데스",
"Oviedo": "오비에도",
"Racing Santander": "라싱 산탄데르",
"Tenerife": "테네리페",
"Zaragoza": "사라고사",
"Darmstadt 98": "다름슈타트",
"FC Koln": "쾰른",
"Fortuna Düsseldorf": "뒤셀도르프",
"Greuther Furth": "그로이터 퓌르트",
"Hamburger SV": "함부르크",
"Hannover 96": "하노버",
"Hertha Berlin": "헤르타 베를린",
"Jahn Regensburg": "얀 레겐스부르크",
"Kaiserslautern": "카이저슬라우테른",
"Karlsruher SC": "카를스루에",
"Magdeburg": "마그데부르크",
"Nurnberg": "뉘른베르크",
"Paderborn 07": "파더보른",
"Preussen Munster": "프로이센 뮌스터",
"Schalke 04": "샬케",
"SV Elversberg": "엘버스베르크",
"Ulm": "울름",
"Eintracht Braunschweig": "브라운슈바이크",
"Bari": "바리",
"Brescia": "브레시아",
"Carrarese": "카라레세",
"Catanzaro": "카탄차로",
"Cesena": "체세나",
"Cittadella": "치타델라",
"Cosenza": "코센차",
"Cremonese": "크레모네세",
"Frosinone": "프로시노네",
"Juve Stabia": "유베 스타비아",
"Mantova": "만토바",
"Modena": "모데나",
"Palermo": "팔레르모",
"Pisa": "피사",
"Reggiana": "레지아나",
"Salernitana": "살레르니타나",
"Sampdoria": "삼프도리아",
"Sassuolo": "사수올로",
"Spezia": "스페치아",
"Sudtirol": "쥐트티롤",
"Ajaccio": "아작시오",
"Amiens": "아미앵",
"Annecy": "안시",
"Bastia": "바스티아",
"Caen": "캉",
"Clermont": "클레르몽",
"Dunkerque": "됭케르크",
"Grenoble": "그르노블",
"Guingamp": "갱강",
"Laval": "라발",
"Lorient": "로리앙",
"Martigues": "마르티그",
"Metz": "메스",
"Paris FC": "파리 FC",
"Pau": "포",
"Red Star": "레드 스타",
"Rodez": "로데즈",
"Troyes": "트루아",
"Ulsan HD": "울산 HD",
"Pohang Steelers": "포항 스틸러스",
"Gwangju FC": "광주 FC",
"Jeonbuk Motors": "전북 현대",
"Daegu FC": "대구 FC",
"Incheon United": "인천 유나이티드",
"FC Seoul": "FC 서울",
"Daejeon Citizen": "대전 하나시티즌",
"Jeju United": "제주 유나이티드",
"Gangwon FC": "강원 FC",
"Suwon FC": "수원 FC",
"Gimcheon Sangmu": "김천 상무",
"Suwon Bluewings": "수원 삼성 블루윙즈",
"Busan I'Park": "부산 아이파크",
"Gyeongnam FC": "경남 FC",
"Bucheon FC 1995": "부천 FC 1995",
"FC Anyang": "FC 안양",
"Jeonnam Dragons": "전남 드래곤즈",
"Chungbuk Cheongju": "충북 청주",
"Seongnam FC": "성남 FC",
"Chungnam Asan": "충남 아산",
"Seoul E-Land": "서울 이랜드",
"Gimpo FC": "김포 FC",
"Ansan Greeners": "안산 그리너스",
"Cheonan City": "천안 시티",
"Vissel Kobe": "비셀 고베",
"Yokohama F. Marinos": "요코하마 F. 마리노스",
"Kawasaki Frontale": "가와사키 프론탈레",
"Sanfrecce Hiroshima": "산프레체 히로시마",
"Kashima Antlers": "가시마 앤틀러스",
"Nagoya Grampus": "나고야 그램퍼스",
"Urawa Red Diamonds": "우라와 레드 다이아몬즈",
"Cerezo Osaka": "세레소 오사카",
"Albirex Niigata": "알비렉스 니가타",
"Avispa Fukuoka": "아비스파 후쿠오카",
"Gamba Osaka": "감바 오사카",
"FC Tokyo": "FC 도쿄",
"Tokyo Verdy": "도쿄 베르디",
"Machida Zelvia": "마치다 젤비아",
"Jubilo Iwata": "주빌로 이와타",
"Kyoto Sanga": "교토 상가",
"Sagan Tosu": "사간 도스",
"Shonan Bellmare": "쇼난 벨마레",
"Kashiwa Reysol": "가시와 레이솔",
"Consadole Sapporo": "콘사도레 삿포로",
"Shimizu S-Pulse": "시미즈 S-펄스",
"Yokohama FC": "요코하마 FC",
"Ventforet Kofu": "반포레 고후",
"Montedio Yamagata": "몬테디오 야마가타",
"JEF United Chiba": "제프 유나이티드 지바",
"V-Varen Nagasaki": "V-바렌 나가사키",
"Oita Trinita": "오이타 트리니타",
"Fagiano Okayama": "파지아노 오카야마",
"Thespa Gunma": "더스파 군마",
"Vegalta Sendai": "베갈타 센다이",
"Blaublitz Akita": "블라우블리츠 아키타",
"Roasso Kumamoto": "로아소 구마모토",
"Tokushima Vortis": "도쿠시마 보르티스",
"Mito Hollyhock": "미토 홀리호크",
"Iwaki FC": "이와키 FC",
"Fujieda MYFC": "후지에다 MYFC",
"Tochigi SC": "도치기 SC",
"Renofa Yamaguchi": "레노파 야마구치",
"Kagoshima United": "가고시마 유나이티드",
"Ehime FC": "에히메 FC",
"Shanghai Port": "상하이 포트",
"Shanghai Shenhua": "상하이 선화",
"Shandong Taishan": "산둥 타이산",
"Zhejiang Professional": "저장 프로페셔널",
"Chengdu Rongcheng": "청두 룽청",
"Beijing Guoan": "베이징 궈안",
"Wuhan Three Towns": "우한 싼전",
"Tianjin Jinmen Tiger": "톈진 진먼 타이거",
"Changchun Yatai": "창춘 야타이",
"Henan": "허난",
"Meizhou Hakka": "메이저우 하카",
"Cangzhou Mighty Lions": "창저우 마이티 라이온즈",
"Qingdao Hainiu": "칭다오 하이뉴",
"Nantong Zhiyun": "난퉁 즈윈",
"Shenzhen Peng City": "선전 펑시티",
"Qingdao West Coast": "칭다오 웨스트코스트",
"Guangxi Pingguo Haliao": "광시 핑궈 할랴오",
"Nanjing City": "난징 시티",
"Shijiazhuang Gongfu": "스자좡 궁푸",
"Suzhou Dongwu": "쑤저우 둥우",
"Yanbian Longding": "옌볜 룽딩",
"Heilongjiang Ice City": "헤이룽장 아이스시티",
"Shanghai Jiading Huilong": "상하이 자딩 후이룽",
"Liaoning Tieli": "랴오닝 톄리",
"Guangzhou FC": "광저우 FC",
"Yunnan Yukun": "윈난 위쿤",
"Dalian Young Boy": "다롄 영 보이",
"Chongqing Tonglianglong": "충칭 퉁량룽",
"Wuxi Wugo": "우시 우거",
"Jiangxi Lushan": "장시 루산",
"Foshan Nanshi": "포산 난스", "RB Salzburg": "잘츠부르크", "Shakhtar Donetsk": "샤흐타르", "Sparta Praha": "스파르타 프라하", "Sturm Graz": "슈투름 그라츠", "Slovan Bratislava": "슬로반 브라티슬라바",
"FK Crvena Zvezda": "즈베즈다", "Cerro Porteno": "세로 포르테뇨", "Kifisia": "키피시아", "Al-Ahli Jeddah": "알 아흘리 제다", "Ghazl El Mehalla": "가즐 엘 마할라", "El Gouna FC": "엘 구나 FC",
"Haras El Hodood": "하라스 엘 호두드", "Future FC": "퓨처 FC", "Wadi Degla": "와디 데글라", "Pharco": "파르코", "Orange County SC": "오렌지 카운티 SC", "San Antonio": "샌안토니오 FC",
"Lokomotiv Sofia": "로코모티브 소피아"
};

export default async function handler(req: VercelRequest, res: VercelResponse) {
  res.setHeader('Cache-Control', 's-maxage=15, stale-while-revalidate');
  res.setHeader('Access-Control-Allow-Origin', '*');

  const { date } = req.query;
  const targetDateStr = typeof date === 'string' ? date : new Date().toISOString().split('T')[0];

  try {
    const prevDate = new Date(targetDateStr);
    prevDate.setDate(prevDate.getDate() - 1);
    const prevDateStr = prevDate.toISOString().split('T')[0];

    const fetchAPI = (endpoint: string, params: string) => 
      fetch(`https://v3.football.api-sports.io/${endpoint}?${params}`, { 
        headers: { 'x-rapidapi-key': API_KEY || '', 'x-rapidapi-host': 'v3.football.api-sports.io' } 
      }).then(r => r.json());

    // 경기 정보와 배당 정보를 각각 오늘/전날치 가져옴
    const [targetData, prevData, targetOdds, prevOdds] = await Promise.all([
      fetchAPI('fixtures', `date=${targetDateStr}`),
      fetchAPI('fixtures', `date=${prevDateStr}`),
      fetchAPI('odds', `date=${targetDateStr}`),
      fetchAPI('odds', `date=${prevDateStr}`)
    ]);

    const allMatches = [...(targetData.response || []), ...(prevData.response || [])];
    const allOdds = [...(targetOdds.response || []), ...(prevOdds.response || [])];

    // [개선] 배당 데이터 맵핑 (Bet365 없으면 다른 북메이커라도 찾기)
    const oddsMap: any = {};
    allOdds.forEach((o: any) => {
      // 1순위 Bet365, 없으면 첫번째 북메이커 사용
      const bookmaker = o.bookmakers.find((b: any) => b.name === 'Bet365') || o.bookmakers[0];
      const market = bookmaker?.bets.find((b: any) => b.name === 'Match Winner' || b.name === '1x2');
      if (market) {
        oddsMap[o.fixture.id] = {
          home: market.values.find((v: any) => v.value === 'Home' || v.value === '1')?.odd,
          draw: market.values.find((v: any) => v.value === 'Draw' || v.value === 'X')?.odd,
          away: market.values.find((v: any) => v.value === 'Away' || v.value === '2')?.odd
        };
      }
    });

    const filteredMatches = allMatches
      .filter((item: any) => {
        if (leagueNameMap[item.league.id] === undefined) return false;
        const matchDateKST = new Date(item.fixture.date).toLocaleDateString('en-CA', { timeZone: 'Asia/Seoul' });
        return matchDateKST === targetDateStr;
      })
      .map((item: any) => {
        const hName = item.teams.home.name;
        const aName = item.teams.away.name;
        
        return {
          id: item.fixture.id,
          timestamp: item.fixture.timestamp,
          league: leagueNameMap[item.league.id],
          // [팀 이름 처리] 맵에 있으면 한글, 없으면 영문 유지
          home: teamNameMap[hName] || hName,
          away: teamNameMap[aName] || aName,
          scoreHome: item.goals.home ?? 0,
          scoreAway: item.goals.away ?? 0,
          status: item.fixture.status.short,
          elapsed: item.fixture.status.elapsed,
          korTime: new Date(item.fixture.date).toLocaleTimeString('ko-KR', { hour: '2-digit', minute: '2-digit', hour12: false, timeZone: 'Asia/Seoul' }),
          predict: { home: Math.round((item.fixture.id % 15) / 10 + 1.2), away: Math.round(((item.fixture.id / 10) % 15) / 10 + 0.8) },
          probs: { home: 40, draw: 30, away: 30 },
          odds: oddsMap[item.fixture.id] || null
        };
      })
      .sort((a: any, b: any) => {
        const statusOrder: any = { 'LIVE': 0, '1H': 0, 'HT': 0, '2H': 0, 'ET': 0, 'P': 0, 'BT': 0, 'NS': 1, 'FT': 2 };
        const orderA = statusOrder[a.status] ?? 3;
        const orderB = statusOrder[b.status] ?? 3;
        if (orderA !== orderB) return orderA - orderB;
        return a.timestamp - b.timestamp;
      });

    return res.status(200).json({ matches: filteredMatches });
  } catch (error) {
    return res.status(200).json({ matches: [] });
  }
}
